name: 'Update docker-compose.yml and docker-compose.override.yml'
description: 'Update image versions in docker-compose.yml and docker-compose.override.yml, build and push image'

inputs:
  registry:
    description: 'Server address of container registry'
    required: true
    default: "docker.io"
  registry-user:
    description: 'User name for container registry'
    required: true
  registry-pass:
    description: 'Password for container registry'
    required: true
  working-directory:
    description: 'Working directory'
    required: true
    default: "."
  bake-action:
    description: 'Buildx bake action ("load" to local cache or "push" to registry)'
    required: true
    default: "load"

outputs:
  services-rebuilt:
    description: "Services in docker-compose.override.yml that were rebuilt"
    value: ${{ steps.update-tags.outputs.services-to-rebuild }}

runs:
  using: "composite"
  steps:
    - name: Update docker-compose files and get services to rebuild
      id: update-tags
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        set -x
        pip install -r ${{ github.action_path }}/requirements.txt
        python ${{ github.action_path }}/update_tags.py -a "${{ inputs.bake-action }}"

    - name: Set up QEMU
      if: steps.update-tags.outputs.services-to-rebuild != '' && inputs.bake-action == 'push'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: steps.update-tags.outputs.services-to-rebuild != ''
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Registry
      if: steps.update-tags.outputs.services-to-rebuild != '' && inputs.bake-action == 'push'
      uses: docker/login-action@v3
      with:
        registry: ${{inputs.registry}}
        username: ${{inputs.registry-user}}
        password: ${{inputs.registry-pass}}

    - name: Rebuild and push images
      if: steps.update-tags.outputs.services-to-rebuild != ''
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        set -x

        BUILD_COMMAND="docker buildx bake -f docker-compose.yml -f docker-compose.override.yml ${{ steps.update-tags.outputs.services-to-rebuild }} \
                      --set *.cache-to=type=local,mode=max,dest=/tmp/.buildx-cache --set *.cache-from=type=local,src=/tmp/.buildx-cache"

        if [ "${{ github.event_name }}" != "push" ] || [ "${{ inputs.bake-action }}" == "load" ]; then
          # just build for local tests on PRs
          $BUILD_COMMAND --load --set "*.platform=linux/amd64"
        elif [ "${{ github.event_name }}" == "push" ]; then
          # build for all platforms and push to registry on pushes
          $BUILD_COMMAND --push
        else
          echo "Unknown bake action: ${{ inputs.bake-action }}"
          exit 1
        fi
